language: node_js

node_js:
  - "8"

cache: npm

# npm test is executed here by default

deploy:
  provider: npm # deploys to npmjs repo
  email: # travis secure - to be updated per travis repo
    secure: nUlJFUlYaOmaoC/vBSeM967LsfGuYXrlrLWrNiT9Giu6CjA8x1bHnpguPAhVqQlMDJtzUS4rfEFwNQG58/EdPP5/LxZh1gSWNV5hClMFOH8JHnFpWqugpD2+gIUreS5BhJuDVXyFA+669aBnUnfT3yyQ9EG16weSdUBboH0k4qcQTtdXG/pL7JsSughPDimwyLijKBqx3HAGrQzcazlBZEN4OF8fwH5Bq6HRvZRqqltLcfcJi4H+k6dpUkraa5AC+9DrCkHbyChx7qj3hcUlciPl3RbmKXv4VurgsUEvMIKOkLPtyS9IUonPTzsjtTm91BAOjSPn1nGBRyHgFqXTQQlxE70hF1dUp+BTVWUWnjJ6SynAd7TyWOGb6rEp1BYSXLqZr8nb2G7Je8wV8WVF67eFCssWlxaJ3G36B17z+V2xjmzIn2y3iQw2mcD8f65sZRleQADqBE5fSKtAZs5fZbYtm/4TYzj5Gg8TDNNYv7PHLFOTBElEWrfVafdy3pqblDCvb5Ijv4EuCuMwwo+cH5ZsB+zwCOnQTHVKcWukCyMdiDflgngnnajh+ltY1dYoDwM50Ut0Mt/yzFEIQEbr9yhKyWHG0qHK626YnFDy1CyXP2m3GV1BbTKYvZCTclxcVx0X78ylFuy4c1nQI73LGXXuC8Qf6UhP/BcsnZYjNlU=
  api_key: # travis secure - to be updated per travis repo
    secure: RTJJfsh4V+dVlUvCAlDKESOI1GYgeX3z+acpVIzIWjhSofUFPsYADGS0NHFMrK65EmHFDc5oGsEoXFmxLYTIx/m/MQUXuMj8j6t2K8tjK1RgJ+I2J8n6ebBu45DYAj+WeGoAO3cZhdrjG5GtyGGAgS+85PvlsbPOTZ/FMSd5f4RnLjhLGHp546ds+LfVt1HPtbMKMPVRZsLWm1jbrvjAmaLVpm1y+S2UVw9mmcNO4HXn0TADxOvI2o02YbsraY6MRwFl06qkaUmCXGrM5s4lB3+qshBRwszFyiAKnhvJIPftRbqY8u1uHZpy9QJgLxS6Lq9b6UiXkxKfBYX/jxZgbaJrnZ8U8rhijfPbks9+sqtApy+zs0Jz/knUvOvmU8Z5Uerut5ZGKtjS5CJEwjYMPXrrOWp/KepQ4MuYvR9awf+f9N7ASAhLlyse5Qu3T/mWI09Nou2ezWPVS+MJ0WaMHtEsMQfdrly4HLr/cg0jMkZ8+hsIAZy7/F6TFGR9Gh3+58FxYkIRkqbFsfa1gkrecWkrMS6VUnXEscfZtYGBxo96EDB/S6j4VJRLMsnTjlDMmbXkQlqdWKp1GMDLppPhyYMr+nWOfihnvi8DXooh8UKf1n+zswJgrHgFAl2rM4ymHtfHpzMl6gkEpTHFKuAeYFJ8+S+a/px21pltiDfC284=
  on:
    tags: true # only deploys if a git TAG exists for the commit
    # branch: master # only deploys if branch is master